apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "gluetun.fullname" . }}
  labels:
    app: {{ template "gluetun.name" . }}
    chart: {{ template "gluetun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
    {{- if eq .Values.strategyType "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ template "gluetun.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{ toYaml . | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "gluetun.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
             add: [ "NET_ADMIN" ]
          env:
            {{- template "gluetun.other" . }}
            {{- template "gluetun.openvpn" . }}
            {{- template "gluetun.shadowsocks" . }}
            {{- template "gluetun.httpproxy" . }}
            {{- template "gluetun.firewall" . }}
            {{- template "gluetun.dns" . }}
            {{- template "gluetun.httpcontrolserver" . }}
            {{- template "gluetun.health" . }}
